name: cytotorch
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - torchvision
  - torchaudio
  - pyarrow
  - pandas=1.5.3
  - spyder
  - numpy=1.25.0
